config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root'homes#show'
  resources :homes,except: [:show]
  get"home/eat"=>"homes#eat"
  get"home/play"=>"homes#play"
  resources :pictures
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	validates :title, presence:true
	validates :body,presence:true,length: {maximum: 200}



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  validates :name,uniqueness: true,presence:true,length: { minimum:2, maximum: 20}
  validates :body,length: {maximum: 50}

  has_many :books, dependent: :destroy
  attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :authenticate_user!

	def new
		@book=Book.new
	end

	def create
		@book=Book.new(book_params)
		@book.user_id= current_user.id
		if @book.save
		redirect_to books_path, notice:"私も#{@book.title}って本この夏読んでみます。"
	    else
	    @books =Book.all
		@user =current_user
	    render :index
	    end
	end

	def index
		# @books =Book.all.page(params[:page])
		@user =current_user
	    @book =Book.new
        @search = Book.page(params[:page]).ransack(params[:q])
        #ransackはdefaultでbook.allをひろってくるから、book.allはなくても大丈夫。
        #pageはransackよりも先に持ってくる！pageの方がモデルからひろってくるから、拾える範囲が広い？的な
        #controllerを書く順番を変えるだけで結構変わったりするから色々試すべし！
    	@books = @search.result
    end

	def show
		@book =Book.find(params[:id])
		@user =@book.user
	    @booker =Book.new
	end

	def destroy
		@book =Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	def edit
	    @book = Book.find(params[:id])
    end

    def update
  	    @book =Book.find(params[:id])
  	    if @book.update(book_params)
		redirect_to book_path(@book.id), notice:"#{@book.title}編集完了！！"
	    else
	    @book = Book.find(params[:id])
	    render :edit
	    end
    end


private
    def book_params
    	params.require(:book).permit(:title,:body,:category)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def index
	end

	def show
	end

	def play
	end

	def eat
	end

	def picture
	end


end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!

  def show
  	user =current_user
	@user =User.find(params[:id])
	@books =@user.books
	@book =Book.new
  end

  def edit
	@user = User.find(params[:id])
  end

  def update
  	@user =User.find(params[:id])
  	if @user.update(user_params)
     redirect_to user_path(@user.id), notice: "#{@user.name}の編集完了!!"
    else
    @books =@user.books
	@book =Book.new
    render :show

    end
  end

  def index
  	@users =User.all
  	@user =current_user
	@book =Book.new

	@search = Book.search(params[:q])
    @books = @search.result(distinct: true)
  end

  def search
    @search = Book.search(search_params)
    @books = @search.result(distinct: true)
  end



private
  def search_params
    params.require(:q).permit!
  end


  def user_params
	params.require(:user).permit(:name,:image, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<%= form_for(book) do |f| %>

<h1>New book</h1>

<label>Title</label>
<div>
  <%= f.text_field :title, class:"book_title col-xs-12", placeholder:"title"%>
</div>

<label><%= f.radio_button :category,"小説" %>小説</label>
<label><%= f.radio_button :category, "ノンフィクション" %>ノンフィクション</label>
<label><%= f.radio_button :category, "料理" %>料理</label>
<label><%= f.radio_button :category, "健康" %>健康</label>
<label><%= f.radio_button :category, "漫画" %>漫画</label>
<label><%= f.radio_button :category, "その他" %>その他</label>

<%#= f.select :category, {'小説' =>1 , 'ノンフィクション' =>2, 'カテゴリ３' => 3} %>

<label>Opinion</label>
<div>
  <%= f.text_area :body,class:"book_body col-xs-12",placeholder:"inpressions,emotions"%>
</div>
<div>
 <%= f.submit"Create Book",class:"btn btn-primary col-xs-12"%>
</div>
<% end %>

app/views/books/edit.html.erb
<div class=container>
<h1>Editing Book</h1>

<%= form_for(@book)do |f| %>
  <div>
   <label>Title</label>
  </div>
  <div>
   <%= f.text_field :title ,autofocus:true, placeholder:"title"%>
  </div>
  <div>
   <label>opinion</label>
  </div>
  <div>
   <%= f.text_area :body, placeholder:"opinion 〜200文字"%>
  </div>
  <div>
   <%= f.submit "Update Book" %>
  </div>
<% end %>
</div>

app/views/books/index.html.erb
<script>var writer = prompt('あなたのオススメの本は何ですか？');
 alert('あなたのオススメの本ならきっと素敵なんだろうなあ。私も今度' + writer + '読んでみますね。教えてくれてありがとう！');
</script>

<div class="container">
	<div class="row">
		<div class="col-lg-4">
			<%= render 'layouts/user_info', user: @user %>
            <%= render 'books/new',book: @book %>
        </div>
		<div class="col-lg-8">
			<%= render 'layouts/error_messages', er:@book %>

<% provide(:title, 'All books') %>

<%= search_form_for(@search, method: :get) do |f| %>
  <div class="form-group">
    <%= f.label :title_cont, "Title" %>
    <%= f.text_field :title_cont, class: "form-control" %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>


			<h1>Books</h1>
            <% @books.each do |book|%>
                <table class="table" style="table-layout:fixed">
  	                <tr>
  		                <th style="width:20%;">&nbsp;</th>
  		                <th style="width:20%;">title</th>
  		                <th style="width:40%;">opinion</th>
  		                <th style="width:20%;">category</th>
  	                </tr>
  	                <tr>
  		                <td><%= attachment_image_tag book.user,:image, fallback: "no_img.jpg", size: '100x100' %></td>
  		                <td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
  		                <td><%= book.body %></td>
  		                <td><%= book.category %></td>
  	                </tr>
                </table>

            <% end %>
			<%= paginate @books, class: "paginate" %>

        </div>
    </div>

</div>

app/views/books/show.html.erb
<script>
            alert('本の詳細ページだよ');
</script>
<h1>git practice
</h1>
<div class="container">
	<div class="row">
		<div class="col-lg-4">
			<%= render 'layouts/user_info', user: @user %>
            <%= render 'books/new',book: @booker %>
        </div>
		<div class="col-lg-8">
			<h1>Book detail</h1>

                <table class="table">
	               <td><%=@book.user.name %></td>
	               <td><%=@book.title %></td>
	               <td><%=@book.body %></td>
	               <td><%=@book.category %></td>
                 <%if @book.user == current_user %>
                   <td><%= link_to "Edit", edit_book_path(@book.id) %></td>
	               <td><%= link_to "Destroy", book_path(@book),method: :delete %></td>
                 <% end %>
                </table>
        </div>
    </div>
</div>

<h2>あああ</h2>

<h3>１２３４５</h3>

<h4>thanks!!</h4>

app/views/homes/about.html.erb
<div class="container">
   <h1>Welcome to <span class="glyphicon glyphicon-book book" ></span><strong>Bookers!</strong></h1>
</div>

<h2>練習</h2>

<h1>aa</h1>

app/views/homes/eat.html.erb
<div class="container">
    <div class="">
         <h1>商品追加</h1>
         <div class="addditem">
	<table>
		<tr>
			<td>年代</td>
			<td><select name="年代">
        	<option value="1860">1980年代前半</option>
        	<option value="1860">1980年代後半</option>
        	<option value="1860">1990年代前半</option>
        	<option value="1860">1990年代後半</option>
        	<option value="1860">2000年代前半</option>
        	<option value="1860">2000年代後半</option>
        	<option value="1860">2010年代後半</option>
        	<option value="1860">2010年代後半</option>
            </select></td>
        </tr>
        <tr>
        <td>アーティスト</td>
			<td><select name="年代">
        	<option value="mrchildren">mr.children</option>
        	<option value="edsheeran">ed sheeran</option>
            </select></td>
        </tr>
        <tr>
            <td>アルバム/シングル名</td>
            <td> <form><input type="text" class="form-control" id="title"></form></td>
        </tr>
        <tr>
            <td>ジャケット画像</td>
            <td><input type="text" class="form-control" id="jacket_image"></td>
            <td><button type="button" class="btn btn-default">選択</button></td>
        </tr>
        <tr>
            <td>値段</td>
            <td> <input type="text" class="form-control" id="price"><p>円</p></td>
        </tr>
        <tr>
            <td>レーベル名</td>
            <td><select name="レーベル名">
            <option value="toys">トイズファクトリー</option>
            <option value="aaaa">あああああ</option>
            </select></td>
        </tr>
        <tr>
            <td>ジャンル</td>
            <td><select name="ジャンル">
            <option value="toys">トイズファクトリー</option>
            <option value="aaaa">あああああ</option>
            </select></td>
        </tr>
        <tr>
            <td>曲名</td>
            <td>Disk 1</td>
            <td><button type="button" class="btn btn-default">選択</button></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td><span>1.</span><input type="text" class="form-control" id="song"></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td><span>2.</span></td>
            <td><input type="text" class="form-control" id="song2"></td>
        </tr>
        <tr>
            <td>在庫数</td>
            <td><input type="text" class="form-control" id="title"><p>枚</p></td>




    </table>

</div>

<button type="button" class="btn btn-default btn-enter">選択</button>

</div>

app/views/homes/index.html.erb
<div class="container">
 <div class="text-white">
 <div class="row">
 <h3 class="cart-title">カート</h3>

 <table class="table table-hover table-bordered">
	<thead>
		<tr>
			<th></th>
			<th>商品名</th>
			<th>アーティスト名</th>
			<th>単価</th>
			<th>数量</th>
			<th>金額（税込)</th>
			<th></th>
		</tr>
	</thead>
	
    
	<tbody>
		<td>ジャケット画像</td>
		<td>キセキ</td>
		<td>GReeeeN</td>
		<td>1,919円</td>
		<td>
            <select class="form-control col-md-6">
            <option value="1" selected="selected">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            </select>
            </div>
　　　　　</td>
		<td>1.919円</td>
		<td>
			<span class="form-inline">
				<%= link_to "削除", carts_index_path, method: :delete,"data-confirm" => "カートから削除しますか？", class: "btn-sm btn-danger" %>
			</span>
		</td>
	</tbody>
 </table>
 </div>
	
    
 <div class="row">
 <div class="col-md-9">
	<%= link_to "お買い物を続ける", root_path, class: "btn-lg btn-primary" %>
 </div>
 <div class="col-md-3">
	<%= link_to "次に進む", root_path, class: "btn-lg btn-success" %>
 </div>
</div>
</div>
 </div>

app/views/homes/picture.html.erb
<div class="container">
	<div class="row">

		<div class="col-lg-8">
			<%= render 'layouts/error_messages', er:@book %>

<% provide(:title, 'All books') %>

<%= search_form_for(@search, method: :get) do |f| %>
  <div class="form-group">
    <%= f.label :title_cont, "Title" %>
    <%= f.text_field :title_cont, class: "form-control" %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>


<h1>商品一覧</h1>





			<h1>Books</h1>
            <% @books.each do |book|%>
                <table class="table" style="table-layout:fixed">
  	                <tr>
  		                <th style="width:20%;">&nbsp;</th>
  		                <th style="width:20%;">title</th>
  		                <th style="width:40%;">opinion</th>
  		                <th style="width:20%;">category</th>
  	                </tr>
  	                <tr>
  		                <td><%= attachment_image_tag book.user,:image, fallback: "no_img.jpg", size: '100x100' %></td>
  		                <td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
  		                <td><%= book.body %></td>
  		                <td><%= book.category %></td>
  	                </tr>
                </table>

            <% end %>
			<%= paginate @books, class: "paginate" %>

        </div>
    </div>

</div>

app/views/homes/play.html.erb
<main role="main" class="flex-shrink-0">
    <div class="container">
      <h1 class="shipping-title text-white">注文の確認</h1>
      <h5 class="text-white mt-5">商品</h5>
      <table class="table text-white">
		  <thead>
		    <tr>
		      <th scope="col"></th>
		      <th scope="col">商品名</th>
		      <th scope="col">アーティスト名</th>
		      <th scope="col">単価</th>
		      <th scope="col">数量</th>
		    </tr>
		  </thead>
		  <tbody>
		    <tr>
		      <td>ジャケット画像</td>
		      <td>HOME</td>
		      <td>Mr.children</td>
		      <td>1900円</td>
		      <td>1</td>
		    </tr>
		    ...
		  </tbody>
	   </table>

	   <h5 class="text-white">配送先</h5>
	   <table class="table text-white">
		  <thead>
		    <tr>
		      <th scope="col">名前</th>
		      <th scope="col">郵便番号</th>
		      <th scope="col">住所</th>
		    </tr>
		  </thead>
		  <tbody>
		    <tr>
		      <td>山田太郎</td>
		      <td>000-0000</td>
		      <td>千葉県浦安市</td>
		    </tr>
		    ...
		  </tbody>
	   </table>
	   <div class="d-flex flex-column">
		   <div class="float-left mt-3">
		   		<button type="button" class="btn btn-danger btn-lg">
		   			<a href="#" class="text-white">注文を確定する</a>
		   		</button>
		   </div>
		   <div class="float-left mt-5">
		   		<button type="button" class="btn btn-light">
		   			<a href="#" class="text-dark">戻る</a>
		   		</button>
		   </div>
	   </div>

    </div>
</main>

app/views/homes/show.html.erb
<div id="container">
   <!-- <div class ="main"> -->
    <div id="theTarget">
      <div class="image1"></div>
      <div class="image2"></div>
      <div class="image3"></div>
      <div class="image4"></div>
      <div class="image5"></div>
    </div>
    <div class="titlehome"><h1>Welcome to TEKAPO</h1></div>
    <div class="subtitle">
    	<h4>Love the life you live<br>
    	    Live the life you love</h4>
    </div>
    <!-- divで箱を作って箱を上下で動かしてそのあとh2で左右を動かすイメージ -->

</div>


<!-- application.jsに貼ってたら、indexとか他のところからhomeに飛ぶときに画像が読み込まなかったけど、↓みたいにhtmlに直接入れると読み込みが早くなって？しっかりと画像を読み込むことができる。書く場所変えるのあり！ -->
<script>

	$(document).ready(function () {
  $("#theTarget").skippr({
      // スライドショーの変化 ("fade" or "slide")
      transition : 'slide',
      // 変化に係る時間(ミリ秒)
      speed : 1000,
      // easingの種類
      easing : 'easeOutQuart',
      // ナビゲーションの形("block" or "bubble")
      navType : 'block',
      // 子要素の種類("div" or "img")
      childrenElementType : 'div',
      // ナビゲーション矢印の表示(trueで表示)
      arrows : true,
      // スライドショーの自動再生(falseで自動再生なし)
      autoPlay : true,
      // 自動再生時のスライド切替間隔(ミリ秒)
      autoPlayDuration : 3000,
      // キーボードの矢印キーによるスライド送りの設定(trueで有効)
      keyboardOnAlways : true,
      // 一枚目のスライド表示時に戻る矢印を表示するかどうか(falseで非表示)
      hidePrevious : false
  });
});
</script>

app/views/layouts/_error_messages.html.erb
<% if er.errors.any? %>
  <div class="alert alert-warning">
  	<h2><%= er.errors.count %>件のエラーがあります</h2>
    <ul>
      <% er.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom navbar-inverse">
  <div class="container">
    <nav>
      <div class="slidemenu">
        <p class="nav navbar-nav navbar-left">© recommended by ASAHI</p>
      </div>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class= "navbar navbar-fixed-top navbar-inverse">
<div class="container">
    <nav>
      <div class="slidemenu">
        <ul class="nav navbar-nav navbar-left" data-hover="dropdown">
          <font size="6" color="white"><%= link_to "TEKAPO", root_path %></font>
        </ul>
        <ul class="nav navbar-nav navbar-right" data-hover="dropdown">
           <li><%= link_to "テカポの魅力！！", homes_path, class:"glyphicon glyphicon-heart" %></li>
           <li><%= link_to "美味しいご飯", home_eat_path, class:"glyphicon glyphicon-cutlery"  %></li>
           <li><%= link_to "遊び方", home_play_path, class:"glyphicon glyphicon-globe"  %></li>
           <li><%= link_to "写真", pictures_path, class:"glyphicon glyphicon-camera"  %></li>
      </ul>
      </div>
    </nav>
</div>
</header>

app/views/layouts/_search.html.erb
<p>検索</p>
<%= form_tag(search_path,:method => 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>

<ul><% @books.each do |book| %>
  <li>
    <%= link_to book.title, book %>
    <%= book.created_at %>
    <%= book.status %>
  </li>
  <%= link_to "編集",edit_book_path(book) %>
  <%= link_to "削除",book, method: :delete %>
  <% end %>
</ul>

app/views/layouts/_user_info.html.erb
<h1>User info</h1>
<%= attachment_image_tag user,:image, fallback: "no_img.jpg",size:'20×20' %>
<table class="table">
  <tr>
	<td>name</td>
	<td><%=user.name %></td>
  </tr>
  <tr>
  	<td>introduction</td>
  	<td><%=user.body %></td>
  </tr>
</table>

<%= link_to  edit_user_path(user.id), class: "btn btn-primary btn-block edit_user_#{user.id}" do %><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tekapo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

　<body>
  <%= render 'layouts/header'%>



 <%= yield %>

 <%= render 'layouts/footer'%>

  </body>
</html>

app/views/pictures/index.html.erb
<h1>Find! YOUR FAVORITE PHOTO!!</h1>

app/views/users/_search.html.erb
<!-- = search_form_for(@q, url:search_path) do |f|
  p
    = f.label :department_id_eq, '学部'
    = f.collection_radio_buttons :department_id_eq, @departments, :id, :name
  = f.submit -->

  <div class="field">
  <span class="book_category">好きな本のジャンルは？？</span><br>
  <div class="radio-inline">
    <%= f.radio_button :category, :小説, checked: "checked" %>
    <%= f.label :小説, class: "category_label" %>
  </div>
  <div class="radio-inline">
    <%= f.radio_button :category, :ノンフィクション %>
    <%= f.label :ノンフィクション, class: "category_label" %>
  </div>
  <div class="radio-inline">
    <%= f.radio_button :category, :料理 %>
    <%= f.label :料理, class: "category_label" %>
  </div>
  <div class="radio-inline">
    <%= f.radio_button :category, :健康 %>
    <%= f.label :健康, class: "category_label" %>
  </div>
  <div class="radio-inline">
    <%= f.radio_button :category, :漫画 %>
    <%= f.label :漫画, class: "category_label" %>
  </div>
  <div class="radio-inline">
    <%= f.radio_button :category, :その他 %>
    <%= f.label :その他, class: "category_label" %>
  </div>
</div>

app/views/users/edit.html.erb
<div class ="container">

<h1>User info</h1>

<%= form_for(@user)do |f| %>
   <label>Name</label>
   <%= f.text_field :name ,autofocus:true, placeholder:"name 2〜20文字"%>
   <div><label>Image</label></div>
   <%= f.attachment_field :image, placeholder:"profile_image"%>
   <div><label>introduction</label>
      <%= f.text_area :body, placeholder:"introduction 〜50文字"%>
   </div>
   <div>
      <%= f.submit "Update User"%>
   </div>
<% end %>
</div>

app/views/users/index.html.erb
<script>alert('本が好きな人たちが集まってるよ');</script>
<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <%= render 'layouts/user_info', user: @user %>
      <%= render 'books/new',book: @book %>
    </div>
    <div class="col-lg-8">

<strong>本のジャンル</strong><br>
<%= f.hidden_field :category %>
<%= @book.category %>

      <h1>Users</h1>
        <% @users.each do |users|%>
          <table class="table">
  	        <tr>
  		        <th style="width:100px;">image</th>
  		        <th style="width:150px;">name</th>
              <th style="width:200px;">&nbsp;</th>
  	        </tr>
  	        <tr>
  		        <td><%= attachment_image_tag users,:image, fallback: "no_img.jpg", size: '100x100' %></td>
  		        <td><%= users.name %></td>
  		        <td><%= link_to 'Show', user_path(users.id)%></td>
  	        </tr>
          </table>
        <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-4">
			<%= render 'layouts/user_info', user: @user %>
            <%= render 'books/new',book: @book %>
        </div>
		<div class="col-lg-8">
			<%= render 'layouts/error_messages', er:@user %>
            <h1>Books</h1>
                <% @books.each do |book|%>
                    <table class="table">
  	                    <tr>
  		                    <th style="width:150px;">&nbsp;</th>
  		                    <th style="width:150px;">title</th>
  		                    <th style="width:200px;">opinion</th>
  		                    <th style="width:100px;">category</th>
  	                    </tr>
  	                    <tr>
  		                    <td><%= attachment_image_tag @user,:image, fallback: "no_img.jpg", size: '100x100' %></td>
  		                    <td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
  		                    <td><%= book.body %></td>
  		                    <td><%= book.category %></td>
  	                    </tr>
                    </table>
                <% end %>
        </div>
    </div>
</div>